export const MOVIE_DB_BASE_URL = 'https://api.themoviedb.org/3'
export const API_KEY = 'acf0a46c4b8431cdbc95e10c7c33e974'
export const IMG_BASE_URL_w185 = 'https://image.tmdb.org/t/p/w185/'
export const IMG_BASE_URL_ORIGINAL = 'https://image.tmdb.org/t/p/original'
export const BANNER_GENRE_KEY = 'Top Rated'